# docker-compose.yml (Base Configuration)
# Defines the core service structure and network for all environments.

services:
  # --- Vault Service Placeholder ---
  vault:
    image: hashicorp/vault:1.19.2 # Use specific version
    container_name: vault # Generic name, override will add '-dev'
    networks:
      - amlume-shop-network
    # Base environment vars (if any common ones exist)
    environment:
      VAULT_ADDR: http://vault:8200 # Internal address

  # --- Auth Database Service Placeholder ---
  mysql-auth:
    image: bitnami/percona-mysql # Or your preferred image/version
    container_name: mysql-auth
    networks:
      - amlume-shop-network
    # No ports, volumes, or env vars here - defined in overrides

  # --- Shop Database Service Placeholder ---
  mysql-shop:
    image: bitnami/percona-mysql # Or your preferred image/version
    container_name: mysql-shop
    networks:
      - amlume-shop-network
    # No ports, volumes, or env vars here - defined in overrides

  # --- Valkey Cache Service Placeholder ---
  valkey-cache:
    image: valkey/valkey:latest
    container_name: valkey-cache
    networks:
      - amlume-shop-network
    # No ports, volumes, or command here - defined in overrides

  # --- Auth Server Application Placeholder (for Production) ---
  auth-server:
    # Build context/image defined in overrides
    container_name: auth-server
    networks:
      - amlume-shop-network
    # Ports/Env vars defined in overrides

  # --- Shop Application Placeholder (for Production) ---
  shop-app:
    # Build context/image defined in overrides
    container_name: shop-app
    networks:
      - amlume-shop-network
    # Ports/Env vars defined in overrides

# --- Volumes Definition ---
# Define named volumes that might be used in any environment
volumes:
  vault_config: {} # If using file backend in prod
  vault_data: {}   # If using file backend in prod
  vault_logs: {}
  mysql-auth-data: {}
  mysql-auth-logs: {}
  mysql-shop-data: {}
  mysql-shop-logs: {}
  mysql-backups: {} # If used in prod/dev
  valkey_data: {}

# --- Network Definition ---
networks:
  amlume-shop-network:
    name: amlume-shop-network