# src/main/resources/k8s/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: amlume-shop-secrets
type: Opaque
data:
  recaptcha-secret: <base64-encoded-secret>
  recaptcha-site-key: <base64-encoded-site-key>
  valkey-secret: <base64-encoded-valkey-secret>
  valkey-url: <base64-encoded-valkey-url>
  valkey-user: <base64-encoded-valkey-user>
  valkey-password: <base64-encoded-valkey-password>