apiVersion: apps/v1
kind: Deployment
metadata:
  name: asn-lookup-service
  labels:
    app: asn-lookup-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asn-lookup-service
  template:
    metadata:
      labels:
        app: asn-lookup-service
    spec:
      containers:
        - name: asn-lookup-service
          image: your-registry/asn-lookup-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: geoip-database
              mountPath: /app/GeoLite2-ASN.mmdb
              subPath: GeoLite2-ASN.mmdb
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"
      volumes:
        - name: geoip-database
          configMap:
            name: geoip-database
