# src/main/resources/k8s/kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yml
  - deployment.yml
  - service.yml
  - secret.yml

commonLabels:
  app: amlume-shop
