services:
  mysql:
    image: 'bitnami/percona-mysql'
    environment:
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MYSQL_USER: ${AUTH_DB_USER}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
    ports:
      - '3406'
#      - '3306'
